description: A Yeager Component that processes the uploaded documents from WritingSamplesUpload
  and extracts the text content from them. The TextExtractor is designed to handle
  a variety of document formats, such as PDF, DOCX, and TXT files, and to convert
  the extracted text into a plain text format for further processing in the workflow.
name: TextExtractor
parameters:
  max_file_size: 10MB
